# Generated by Django 3.1.3 on 2020-12-19 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)])),
                ('item_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('title_auction', models.CharField(max_length=80)),
                ('auction_format', models.IntegerField(blank=True, choices=[(0, 'daily'), (1, 'weekly'), (2, 'daily & weekly')], default=None, null=True)),
                ('img_auction', models.URLField(max_length=150)),
                ('seller_comment', models.TextField(default='', max_length=250)),
                ('auction_account', models.CharField(max_length=20)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_downloaded', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.EmailField(max_length=254)),
                ('company_accounts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_stock', models.IntegerField(default=0)),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_uvp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ebapp.auctions')),
            ],
        ),
    ]
