# Generated by Django 3.1.3 on 2020-12-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='auction_format',
        ),
        migrations.AddField(
            model_name='auctionsdetails',
            name='auction_format',
            field=models.IntegerField(blank=True, choices=[(0, 'daily'), (1, 'weekly'), (2, 'daily & weekly')], default=None, null=True),
        ),
    ]
