# Generated by Django 3.1.3 on 2020-12-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0002_auto_20201219_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ebay_category',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='target_website_for_wow_offer',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionsdetails',
            name='auction_format',
            field=models.IntegerField(blank=True, choices=[(0, 'wow! angebot des tages'), (1, 'wow! angebot der woche'), (2, 'BOTH')], default=None, null=True),
        ),
    ]
