# Generated by Django 3.1.3 on 2020-12-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0003_auto_20201222_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='item_id',
            new_name='private_id',
        ),
    ]
