# Generated by Django 3.1.3 on 2020-12-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0004_auto_20201222_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='company_accounts',
            field=models.TextField(),
        ),
    ]
