# Generated by Django 3.1.3 on 2020-12-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0005_auto_20201222_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ebay_category',
            field=models.TextField(),
        ),
    ]
