# Generated by Django 3.1.3 on 2020-12-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0006_auto_20201225_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='auction_account',
        ),
    ]
