# Generated by Django 3.1.3 on 2020-12-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0007_remove_auctions_auction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='auction_account',
            field=models.CharField(default='ozonee-store', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctions',
            name='ebay_category',
            field=models.CharField(default='Kleidung & Accessoires', max_length=150),
            preserve_default=False,
        ),
    ]
