# Generated by Django 3.1.4 on 2020-12-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0008_auto_20201225_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='seller_comment',
            field=models.TextField(default='', max_length=250, null=True),
        ),
    ]
