# Generated by Django 3.1.4 on 2020-12-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0010_auto_20201227_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='seller_comment',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
