# Generated by Django 3.1.4 on 2020-12-28 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0011_auto_20201227_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='private_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
