# Generated by Django 3.1.4 on 2020-12-28 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0012_auto_20201228_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='external_id',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
