# Generated by Django 3.1.4 on 2020-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0014_auctions_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='selected',
            field=models.IntegerField(choices=[(0, 'Not selected'), (1, 'Selected')], default=0),
        ),
    ]
