# Generated by Django 3.1.4 on 2021-01-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0016_auctions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_account', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EbayCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='auctions',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Not Confirmed')], default=0),
        ),
    ]
