# Generated by Django 3.1.4 on 2021-01-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0017_auto_20210103_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyAccount',
            new_name='CompanyAccounts',
        ),
    ]
