# Generated by Django 3.1.4 on 2021-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0019_auto_20210104_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccounts',
            name='company_account',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ebaycategories',
            name='ebay_category',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
