# Generated by Django 3.1.4 on 2021-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0020_auto_20210104_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='archived',
            field=models.IntegerField(choices=[(0, 'Not selected'), (1, 'Selected')], default=0),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not archived'), (1, 'Archived')], default=0),
        ),
    ]
