# Generated by Django 3.1.4 on 2021-02-02 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebapp', '0022_companyaccounts_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='archived',
            field=models.IntegerField(choices=[(0, 'Not archived'), (1, 'Archived')], default=0),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Not Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='auctionsdetails',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_rel', to='ebapp.auctions'),
        ),
    ]
